### ISSUE TITLE
Wrong exposed port (1234) instead of 5000

### ISSUE THREAD

**Issue by ludydoo** [sysdiglabs/aks-audit-log#6]
It seems that the exposed metrics port in the Dockerfile (1234) does not match the Prometheus port (5000)

````
Server = new MetricServer(port: 5000);
````

````
prometheus.io/path: /metrics
prometheus.io/port: "5000"
````

```
          readinessProbe:
            exec:
              command:
                - wget
                - localhost:1234/metrics
                - --spider
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 1234
            initialDelaySeconds: 10
            periodSeconds: 20
```
